### ISSUE TITLE
"all in one install" with bundled ArgoCD and Bitnami 

### ISSUE THREAD

**Issue by mciverza** [lsdopen/charts#25]
add an option for an "batteries included" installation of Ahoy that will include
Bitnami Sealed-Secrets and ArgoCD as well.

**Comment by clivebor** [comment]
hey @mciverza 
It is an all-in-one install already; if you look at the chart you'll see that Sealed-Secrets and ArgoCD are dependencies, as well as Postgres and Keycloak, which you can decide to install or not by defining so in the values file.. 👍
